// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goqueue.proto

package goqueuev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Partition     int32                  `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_goqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublishRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_goqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PublishResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_goqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConsumeRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type ConsumeMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Offset            int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Payload           []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Partition         int32                  `protobuf:"varint,4,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConsumeMessage) Reset() {
	*x = ConsumeMessage{}
	mi := &file_goqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeMessage) ProtoMessage() {}

func (x *ConsumeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeMessage.ProtoReflect.Descriptor instead.
func (*ConsumeMessage) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConsumeMessage) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *ConsumeMessage) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type FetchRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Topic      string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition  int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	FromOffset int64                  `protobuf:"varint,3,opt,name=from_offset,json=fromOffset,proto3" json:"from_offset,omitempty"`
	// Maximum messages to return. Server caps at 4096.
	MaxCount int32 `protobuf:"varint,4,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	// Optional server-side filter. When set, the broker decodes each
	// candidate message as an agent envelope and returns only matches.
	// Reduces wire bytes drastically for session replay on busy topics.
	// Note: filtering decodes JSON server-side, so it costs CPU per
	// scanned message; broker may scan up to scan_limit messages to
	// produce one page of matches.
	SessionFilter *SessionFilter `protobuf:"bytes,5,opt,name=session_filter,json=sessionFilter,proto3" json:"session_filter,omitempty"`
	// Hard upper bound on messages the broker will scan to fill the
	// requested max_count. Default 16384, max 65536. Has no effect when
	// session_filter is absent.
	ScanLimit     int32 `protobuf:"varint,6,opt,name=scan_limit,json=scanLimit,proto3" json:"scan_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_goqueue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{4}
}

func (x *FetchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FetchRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *FetchRequest) GetFromOffset() int64 {
	if x != nil {
		return x.FromOffset
	}
	return 0
}

func (x *FetchRequest) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *FetchRequest) GetSessionFilter() *SessionFilter {
	if x != nil {
		return x.SessionFilter
	}
	return nil
}

func (x *FetchRequest) GetScanLimit() int32 {
	if x != nil {
		return x.ScanLimit
	}
	return 0
}

// SessionFilter selects events whose envelope matches the given triple.
// All non-empty fields must match (logical AND). Empty fields are wildcards.
type SessionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionFilter) Reset() {
	*x = SessionFilter{}
	mi := &file_goqueue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFilter) ProtoMessage() {}

func (x *SessionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFilter.ProtoReflect.Descriptor instead.
func (*SessionFilter) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{5}
}

func (x *SessionFilter) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *SessionFilter) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SessionFilter) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FetchResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*ConsumeMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// next_offset is the offset to pass on the next page to continue reading.
	// Equals from_offset + len(messages) on success.
	NextOffset int64 `protobuf:"varint,2,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	// head is the oldest offset still retained for this partition (older
	// messages have been evicted from the ring buffer).
	Head int64 `protobuf:"varint,3,opt,name=head,proto3" json:"head,omitempty"`
	// tail is the next-write offset (one past the latest persisted message).
	Tail          int64 `protobuf:"varint,4,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_goqueue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{6}
}

func (x *FetchResponse) GetMessages() []*ConsumeMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *FetchResponse) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *FetchResponse) GetHead() int64 {
	if x != nil {
		return x.Head
	}
	return 0
}

func (x *FetchResponse) GetTail() int64 {
	if x != nil {
		return x.Tail
	}
	return 0
}

// AgentEvent is a structured agent event envelope for the PublishAgent RPC.
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_goqueue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{7}
}

func (x *AgentEvent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AgentEvent) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AgentEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AgentEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAgentRequest) Reset() {
	*x = PublishAgentRequest{}
	mi := &file_goqueue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAgentRequest) ProtoMessage() {}

func (x *PublishAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAgentRequest.ProtoReflect.Descriptor instead.
func (*PublishAgentRequest) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{8}
}

func (x *PublishAgentRequest) GetEvent() *AgentEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PublishAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAgentResponse) Reset() {
	*x = PublishAgentResponse{}
	mi := &file_goqueue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAgentResponse) ProtoMessage() {}

func (x *PublishAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAgentResponse.ProtoReflect.Descriptor instead.
func (*PublishAgentResponse) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{9}
}

func (x *PublishAgentResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PublishAgentResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

// NotLeaderError is returned as a status detail (alongside
// FailedPrecondition) when a client publishes to a node that does not
// own the target shard.
type NotLeaderError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC address (host:port) of the current leader. May be empty if the
	// leader is unknown or unreachable — the SDK should back off and retry.
	LeaderAddr    string `protobuf:"bytes,1,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeaderError) Reset() {
	*x = NotLeaderError{}
	mi := &file_goqueue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeaderError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeaderError) ProtoMessage() {}

func (x *NotLeaderError) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeaderError.ProtoReflect.Descriptor instead.
func (*NotLeaderError) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{10}
}

func (x *NotLeaderError) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type AppendEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	LeaderNodeId  string                 `protobuf:"bytes,4,opt,name=leader_node_id,json=leaderNodeId,proto3" json:"leader_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntry) Reset() {
	*x = AppendEntry{}
	mi := &file_goqueue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntry) ProtoMessage() {}

func (x *AppendEntry) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntry.ProtoReflect.Descriptor instead.
func (*AppendEntry) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{11}
}

func (x *AppendEntry) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *AppendEntry) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AppendEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AppendEntry) GetLeaderNodeId() string {
	if x != nil {
		return x.LeaderNodeId
	}
	return ""
}

type AppendAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	LastOffset    uint64                 `protobuf:"varint,2,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendAck) Reset() {
	*x = AppendAck{}
	mi := &file_goqueue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendAck) ProtoMessage() {}

func (x *AppendAck) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendAck.ProtoReflect.Descriptor instead.
func (*AppendAck) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{12}
}

func (x *AppendAck) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *AppendAck) GetLastOffset() uint64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

func (x *AppendAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type CatchUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	FromOffset    uint64                 `protobuf:"varint,2,opt,name=from_offset,json=fromOffset,proto3" json:"from_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchUpRequest) Reset() {
	*x = CatchUpRequest{}
	mi := &file_goqueue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchUpRequest) ProtoMessage() {}

func (x *CatchUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goqueue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchUpRequest.ProtoReflect.Descriptor instead.
func (*CatchUpRequest) Descriptor() ([]byte, []int) {
	return file_goqueue_proto_rawDescGZIP(), []int{13}
}

func (x *CatchUpRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *CatchUpRequest) GetFromOffset() uint64 {
	if x != nil {
		return x.FromOffset
	}
	return 0
}

var File_goqueue_proto protoreflect.FileDescriptor

const file_goqueue_proto_rawDesc = "" +
	"\n" +
	"\rgoqueue.proto\x12\n" +
	"goqueue.v1\"p\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x1c\n" +
	"\tpartition\x18\x04 \x01(\x05R\tpartition\"G\n" +
	"\x0fPublishResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\"Z\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\"\x90\x01\n" +
	"\x0eConsumeMessage\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12\x1c\n" +
	"\tpartition\x18\x04 \x01(\x05R\tpartition\"\xe1\x01\n" +
	"\fFetchRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x1f\n" +
	"\vfrom_offset\x18\x03 \x01(\x03R\n" +
	"fromOffset\x12\x1b\n" +
	"\tmax_count\x18\x04 \x01(\x05R\bmaxCount\x12@\n" +
	"\x0esession_filter\x18\x05 \x01(\v2\x19.goqueue.v1.SessionFilterR\rsessionFilter\x12\x1d\n" +
	"\n" +
	"scan_limit\x18\x06 \x01(\x05R\tscanLimit\"`\n" +
	"\rSessionFilter\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x90\x01\n" +
	"\rFetchResponse\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.goqueue.v1.ConsumeMessageR\bmessages\x12\x1f\n" +
	"\vnext_offset\x18\x02 \x01(\x03R\n" +
	"nextOffset\x12\x12\n" +
	"\x04head\x18\x03 \x01(\x03R\x04head\x12\x12\n" +
	"\x04tail\x18\x04 \x01(\x03R\x04tail\"\xa6\x01\n" +
	"\n" +
	"AgentEvent\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"C\n" +
	"\x13PublishAgentRequest\x12,\n" +
	"\x05event\x18\x01 \x01(\v2\x16.goqueue.v1.AgentEventR\x05event\"L\n" +
	"\x14PublishAgentResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\"1\n" +
	"\x0eNotLeaderError\x12\x1f\n" +
	"\vleader_addr\x18\x01 \x01(\tR\n" +
	"leaderAddr\"\x80\x01\n" +
	"\vAppendEntry\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12$\n" +
	"\x0eleader_node_id\x18\x04 \x01(\tR\fleaderNodeId\"`\n" +
	"\tAppendAck\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x1f\n" +
	"\vlast_offset\x18\x02 \x01(\x04R\n" +
	"lastOffset\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"L\n" +
	"\x0eCatchUpRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x1f\n" +
	"\vfrom_offset\x18\x02 \x01(\x04R\n" +
	"fromOffset2\xa9\x02\n" +
	"\rBrokerService\x12B\n" +
	"\aPublish\x12\x1a.goqueue.v1.PublishRequest\x1a\x1b.goqueue.v1.PublishResponse\x12C\n" +
	"\aConsume\x12\x1a.goqueue.v1.ConsumeRequest\x1a\x1a.goqueue.v1.ConsumeMessage0\x01\x12<\n" +
	"\x05Fetch\x12\x18.goqueue.v1.FetchRequest\x1a\x19.goqueue.v1.FetchResponse\x12Q\n" +
	"\fPublishAgent\x12\x1f.goqueue.v1.PublishAgentRequest\x1a .goqueue.v1.PublishAgentResponse2\x93\x01\n" +
	"\x0eClusterService\x12?\n" +
	"\tReplicate\x12\x17.goqueue.v1.AppendEntry\x1a\x15.goqueue.v1.AppendAck(\x010\x01\x12@\n" +
	"\aCatchUp\x12\x1a.goqueue.v1.CatchUpRequest\x1a\x17.goqueue.v1.AppendEntry0\x01B0Z.github.com/khangpt2k6/AgentBus/proto;goqueuev1b\x06proto3"

var (
	file_goqueue_proto_rawDescOnce sync.Once
	file_goqueue_proto_rawDescData []byte
)

func file_goqueue_proto_rawDescGZIP() []byte {
	file_goqueue_proto_rawDescOnce.Do(func() {
		file_goqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goqueue_proto_rawDesc), len(file_goqueue_proto_rawDesc)))
	})
	return file_goqueue_proto_rawDescData
}

var file_goqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_goqueue_proto_goTypes = []any{
	(*PublishRequest)(nil),       // 0: goqueue.v1.PublishRequest
	(*PublishResponse)(nil),      // 1: goqueue.v1.PublishResponse
	(*ConsumeRequest)(nil),       // 2: goqueue.v1.ConsumeRequest
	(*ConsumeMessage)(nil),       // 3: goqueue.v1.ConsumeMessage
	(*FetchRequest)(nil),         // 4: goqueue.v1.FetchRequest
	(*SessionFilter)(nil),        // 5: goqueue.v1.SessionFilter
	(*FetchResponse)(nil),        // 6: goqueue.v1.FetchResponse
	(*AgentEvent)(nil),           // 7: goqueue.v1.AgentEvent
	(*PublishAgentRequest)(nil),  // 8: goqueue.v1.PublishAgentRequest
	(*PublishAgentResponse)(nil), // 9: goqueue.v1.PublishAgentResponse
	(*NotLeaderError)(nil),       // 10: goqueue.v1.NotLeaderError
	(*AppendEntry)(nil),          // 11: goqueue.v1.AppendEntry
	(*AppendAck)(nil),            // 12: goqueue.v1.AppendAck
	(*CatchUpRequest)(nil),       // 13: goqueue.v1.CatchUpRequest
}
var file_goqueue_proto_depIdxs = []int32{
	5,  // 0: goqueue.v1.FetchRequest.session_filter:type_name -> goqueue.v1.SessionFilter
	3,  // 1: goqueue.v1.FetchResponse.messages:type_name -> goqueue.v1.ConsumeMessage
	7,  // 2: goqueue.v1.PublishAgentRequest.event:type_name -> goqueue.v1.AgentEvent
	0,  // 3: goqueue.v1.BrokerService.Publish:input_type -> goqueue.v1.PublishRequest
	2,  // 4: goqueue.v1.BrokerService.Consume:input_type -> goqueue.v1.ConsumeRequest
	4,  // 5: goqueue.v1.BrokerService.Fetch:input_type -> goqueue.v1.FetchRequest
	8,  // 6: goqueue.v1.BrokerService.PublishAgent:input_type -> goqueue.v1.PublishAgentRequest
	11, // 7: goqueue.v1.ClusterService.Replicate:input_type -> goqueue.v1.AppendEntry
	13, // 8: goqueue.v1.ClusterService.CatchUp:input_type -> goqueue.v1.CatchUpRequest
	1,  // 9: goqueue.v1.BrokerService.Publish:output_type -> goqueue.v1.PublishResponse
	3,  // 10: goqueue.v1.BrokerService.Consume:output_type -> goqueue.v1.ConsumeMessage
	6,  // 11: goqueue.v1.BrokerService.Fetch:output_type -> goqueue.v1.FetchResponse
	9,  // 12: goqueue.v1.BrokerService.PublishAgent:output_type -> goqueue.v1.PublishAgentResponse
	12, // 13: goqueue.v1.ClusterService.Replicate:output_type -> goqueue.v1.AppendAck
	11, // 14: goqueue.v1.ClusterService.CatchUp:output_type -> goqueue.v1.AppendEntry
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_goqueue_proto_init() }
func file_goqueue_proto_init() {
	if File_goqueue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goqueue_proto_rawDesc), len(file_goqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_goqueue_proto_goTypes,
		DependencyIndexes: file_goqueue_proto_depIdxs,
		MessageInfos:      file_goqueue_proto_msgTypes,
	}.Build()
	File_goqueue_proto = out.File
	file_goqueue_proto_goTypes = nil
	file_goqueue_proto_depIdxs = nil
}
