// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: goqueue.proto

package goqueuev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrokerService_Publish_FullMethodName      = "/goqueue.v1.BrokerService/Publish"
	BrokerService_Consume_FullMethodName      = "/goqueue.v1.BrokerService/Consume"
	BrokerService_Fetch_FullMethodName        = "/goqueue.v1.BrokerService/Fetch"
	BrokerService_PublishAgent_FullMethodName = "/goqueue.v1.BrokerService/PublishAgent"
)

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerServiceClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumeMessage], error)
	// Fetch returns historical messages starting at from_offset. Unlike Consume,
	// it does not track consumer-group state and does not stream - it returns a
	// single page. Use it for session replay, debugging, and time-travel reads.
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	// PublishAgent publishes a structured agent event. In cluster mode, returns
	// FailedPrecondition with a NotLeaderError detail when this node does not
	// own the target shard - the client must redirect to the indicated leader.
	PublishAgent(ctx context.Context, in *PublishAgentRequest, opts ...grpc.CallOption) (*PublishAgentResponse, error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, BrokerService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrokerService_ServiceDesc.Streams[0], BrokerService_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeRequest, ConsumeMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrokerService_ConsumeClient = grpc.ServerStreamingClient[ConsumeMessage]

func (c *brokerServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, BrokerService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) PublishAgent(ctx context.Context, in *PublishAgentRequest, opts ...grpc.CallOption) (*PublishAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAgentResponse)
	err := c.cc.Invoke(ctx, BrokerService_PublishAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility.
type BrokerServiceServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	Consume(*ConsumeRequest, grpc.ServerStreamingServer[ConsumeMessage]) error
	// Fetch returns historical messages starting at from_offset. Unlike Consume,
	// it does not track consumer-group state and does not stream - it returns a
	// single page. Use it for session replay, debugging, and time-travel reads.
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	// PublishAgent publishes a structured agent event. In cluster mode, returns
	// FailedPrecondition with a NotLeaderError detail when this node does not
	// own the target shard - the client must redirect to the indicated leader.
	PublishAgent(context.Context, *PublishAgentRequest) (*PublishAgentResponse, error)
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServiceServer struct{}

func (UnimplementedBrokerServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedBrokerServiceServer) Consume(*ConsumeRequest, grpc.ServerStreamingServer[ConsumeMessage]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedBrokerServiceServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedBrokerServiceServer) PublishAgent(context.Context, *PublishAgentRequest) (*PublishAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishAgent not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}
func (UnimplementedBrokerServiceServer) testEmbeddedByValue()                       {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServiceServer).Consume(m, &grpc.GenericServerStream[ConsumeRequest, ConsumeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrokerService_ConsumeServer = grpc.ServerStreamingServer[ConsumeMessage]

func _BrokerService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_PublishAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).PublishAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_PublishAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).PublishAgent(ctx, req.(*PublishAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goqueue.v1.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _BrokerService_Publish_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _BrokerService_Fetch_Handler,
		},
		{
			MethodName: "PublishAgent",
			Handler:    _BrokerService_PublishAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _BrokerService_Consume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goqueue.proto",
}

const (
	ClusterService_Replicate_FullMethodName = "/goqueue.v1.ClusterService/Replicate"
	ClusterService_CatchUp_FullMethodName   = "/goqueue.v1.ClusterService/CatchUp"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterServiceClient interface {
	// Replicate is a long-lived bidirectional stream from a shard leader to
	// a follower. The leader sends AppendEntry; the follower acks with the
	// last offset it has durably written.
	Replicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppendEntry, AppendAck], error)
	// CatchUp is a one-shot server-streaming RPC used by a follower to
	// backfill entries it is missing before joining the live Replicate
	// stream.
	CatchUp(ctx context.Context, in *CatchUpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AppendEntry], error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppendEntry, AppendAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterService_ServiceDesc.Streams[0], ClusterService_Replicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppendEntry, AppendAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterService_ReplicateClient = grpc.BidiStreamingClient[AppendEntry, AppendAck]

func (c *clusterServiceClient) CatchUp(ctx context.Context, in *CatchUpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AppendEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterService_ServiceDesc.Streams[1], ClusterService_CatchUp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CatchUpRequest, AppendEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterService_CatchUpClient = grpc.ServerStreamingClient[AppendEntry]

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility.
type ClusterServiceServer interface {
	// Replicate is a long-lived bidirectional stream from a shard leader to
	// a follower. The leader sends AppendEntry; the follower acks with the
	// last offset it has durably written.
	Replicate(grpc.BidiStreamingServer[AppendEntry, AppendAck]) error
	// CatchUp is a one-shot server-streaming RPC used by a follower to
	// backfill entries it is missing before joining the live Replicate
	// stream.
	CatchUp(*CatchUpRequest, grpc.ServerStreamingServer[AppendEntry]) error
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServiceServer struct{}

func (UnimplementedClusterServiceServer) Replicate(grpc.BidiStreamingServer[AppendEntry, AppendAck]) error {
	return status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedClusterServiceServer) CatchUp(*CatchUpRequest, grpc.ServerStreamingServer[AppendEntry]) error {
	return status.Error(codes.Unimplemented, "method CatchUp not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}
func (UnimplementedClusterServiceServer) testEmbeddedByValue()                        {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServiceServer).Replicate(&grpc.GenericServerStream[AppendEntry, AppendAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterService_ReplicateServer = grpc.BidiStreamingServer[AppendEntry, AppendAck]

func _ClusterService_CatchUp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CatchUpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterServiceServer).CatchUp(m, &grpc.GenericServerStream[CatchUpRequest, AppendEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterService_CatchUpServer = grpc.ServerStreamingServer[AppendEntry]

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goqueue.v1.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Replicate",
			Handler:       _ClusterService_Replicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CatchUp",
			Handler:       _ClusterService_CatchUp_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goqueue.proto",
}

const (
	ControlPlane_RegisterAgent_FullMethodName   = "/goqueue.v1.ControlPlane/RegisterAgent"
	ControlPlane_Heartbeat_FullMethodName       = "/goqueue.v1.ControlPlane/Heartbeat"
	ControlPlane_OpenInbox_FullMethodName       = "/goqueue.v1.ControlPlane/OpenInbox"
	ControlPlane_GetSessionState_FullMethodName = "/goqueue.v1.ControlPlane/GetSessionState"
	ControlPlane_ListAgents_FullMethodName      = "/goqueue.v1.ControlPlane/ListAgents"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneClient interface {
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// OpenInbox streams events routed to this agent (currently handoffs). The
	// stream stays open until the client disconnects.
	OpenInbox(ctx context.Context, in *OpenInboxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutedEventMsg], error)
	GetSessionState(ctx context.Context, in *SessionStateRequest, opts ...grpc.CallOption) (*RunStateMsg, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*AgentListResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) OpenInbox(ctx context.Context, in *OpenInboxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutedEventMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_OpenInbox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenInboxRequest, RoutedEventMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_OpenInboxClient = grpc.ServerStreamingClient[RoutedEventMsg]

func (c *controlPlaneClient) GetSessionState(ctx context.Context, in *SessionStateRequest, opts ...grpc.CallOption) (*RunStateMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunStateMsg)
	err := c.cc.Invoke(ctx, ControlPlane_GetSessionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*AgentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentListResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
type ControlPlaneServer interface {
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// OpenInbox streams events routed to this agent (currently handoffs). The
	// stream stays open until the client disconnects.
	OpenInbox(*OpenInboxRequest, grpc.ServerStreamingServer[RoutedEventMsg]) error
	GetSessionState(context.Context, *SessionStateRequest) (*RunStateMsg, error)
	ListAgents(context.Context, *ListAgentsRequest) (*AgentListResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) OpenInbox(*OpenInboxRequest, grpc.ServerStreamingServer[RoutedEventMsg]) error {
	return status.Error(codes.Unimplemented, "method OpenInbox not implemented")
}
func (UnimplementedControlPlaneServer) GetSessionState(context.Context, *SessionStateRequest) (*RunStateMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionState not implemented")
}
func (UnimplementedControlPlaneServer) ListAgents(context.Context, *ListAgentsRequest) (*AgentListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_OpenInbox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenInboxRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).OpenInbox(m, &grpc.GenericServerStream[OpenInboxRequest, RoutedEventMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_OpenInboxServer = grpc.ServerStreamingServer[RoutedEventMsg]

func _ControlPlane_GetSessionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetSessionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetSessionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetSessionState(ctx, req.(*SessionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goqueue.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _ControlPlane_RegisterAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "GetSessionState",
			Handler:    _ControlPlane_GetSessionState_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _ControlPlane_ListAgents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenInbox",
			Handler:       _ControlPlane_OpenInbox_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goqueue.proto",
}

const (
	WorkflowService_SubmitWorkflow_FullMethodName      = "/goqueue.v1.WorkflowService/SubmitWorkflow"
	WorkflowService_LeaseTask_FullMethodName           = "/goqueue.v1.WorkflowService/LeaseTask"
	WorkflowService_SubmitWorkflows_FullMethodName     = "/goqueue.v1.WorkflowService/SubmitWorkflows"
	WorkflowService_CompleteTasks_FullMethodName       = "/goqueue.v1.WorkflowService/CompleteTasks"
	WorkflowService_HeartbeatTask_FullMethodName       = "/goqueue.v1.WorkflowService/HeartbeatTask"
	WorkflowService_CompleteTask_FullMethodName        = "/goqueue.v1.WorkflowService/CompleteTask"
	WorkflowService_FailTask_FullMethodName            = "/goqueue.v1.WorkflowService/FailTask"
	WorkflowService_GetExecution_FullMethodName        = "/goqueue.v1.WorkflowService/GetExecution"
	WorkflowService_GetExecutionHistory_FullMethodName = "/goqueue.v1.WorkflowService/GetExecutionHistory"
	WorkflowService_ListExecutions_FullMethodName      = "/goqueue.v1.WorkflowService/ListExecutions"
)

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowServiceClient interface {
	// SubmitWorkflow durably enqueues a new workflow execution. Submitting an
	// id that already exists is an idempotent no-op (already_exists = true).
	// In cluster mode, returns FailedPrecondition with a NotLeaderError detail
	// when this node does not own the execution's shard.
	SubmitWorkflow(ctx context.Context, in *SubmitWorkflowRequest, opts ...grpc.CallOption) (*SubmitWorkflowResponse, error)
	// LeaseTask hands the oldest pending execution of the given task type to a
	// worker. The lease is recorded on the log before the worker sees it. When
	// no work is pending the call long-polls up to wait_ms, then returns
	// found = false. Set max_tasks > 1 to lease a batch in one round trip;
	// every lease is still an individual durable log event.
	LeaseTask(ctx context.Context, in *LeaseTaskRequest, opts ...grpc.CallOption) (*LeaseTaskResponse, error)
	// SubmitWorkflows durably enqueues a batch of executions in one round
	// trip, amortizing RPC overhead for high-rate producers. Each submit is
	// an individual durable log event. In cluster mode every execution in
	// the batch must route to this node.
	SubmitWorkflows(ctx context.Context, in *SubmitWorkflowsRequest, opts ...grpc.CallOption) (*SubmitWorkflowsResponse, error)
	// CompleteTasks records a batch of completions in one round trip; each
	// completion passes the same exactly-once gate as CompleteTask.
	CompleteTasks(ctx context.Context, in *CompleteTasksRequest, opts ...grpc.CallOption) (*CompleteTasksResponse, error)
	// HeartbeatTask extends a running lease. valid = false tells the worker its
	// lease is gone (expired or superseded) and it should abandon the attempt.
	HeartbeatTask(ctx context.Context, in *HeartbeatTaskRequest, opts ...grpc.CallOption) (*HeartbeatTaskResponse, error)
	// CompleteTask records a successful result exactly once. A completion for
	// a stale attempt or an already-terminal execution is rejected with
	// accepted = false (and duplicate = true when the execution already
	// completed), so a zombie worker whose lease expired cannot double-commit.
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	// FailTask records a failed attempt. Retryable failures re-enqueue the
	// execution until max_attempts is exhausted; the response says whether a
	// retry was scheduled.
	FailTask(ctx context.Context, in *FailTaskRequest, opts ...grpc.CallOption) (*FailTaskResponse, error)
	// GetExecution returns the current state of one execution.
	GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*ExecutionStateMsg, error)
	// GetExecutionHistory returns the ordered state transitions of one
	// execution as rebuilt from the event log - the deterministic replay
	// surface used for debugging.
	GetExecutionHistory(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*ExecutionHistoryResponse, error)
	// ListExecutions returns execution summaries, optionally filtered by
	// status, plus in-flight counts.
	ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) SubmitWorkflow(ctx context.Context, in *SubmitWorkflowRequest, opts ...grpc.CallOption) (*SubmitWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowService_SubmitWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) LeaseTask(ctx context.Context, in *LeaseTaskRequest, opts ...grpc.CallOption) (*LeaseTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseTaskResponse)
	err := c.cc.Invoke(ctx, WorkflowService_LeaseTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) SubmitWorkflows(ctx context.Context, in *SubmitWorkflowsRequest, opts ...grpc.CallOption) (*SubmitWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitWorkflowsResponse)
	err := c.cc.Invoke(ctx, WorkflowService_SubmitWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CompleteTasks(ctx context.Context, in *CompleteTasksRequest, opts ...grpc.CallOption) (*CompleteTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTasksResponse)
	err := c.cc.Invoke(ctx, WorkflowService_CompleteTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) HeartbeatTask(ctx context.Context, in *HeartbeatTaskRequest, opts ...grpc.CallOption) (*HeartbeatTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatTaskResponse)
	err := c.cc.Invoke(ctx, WorkflowService_HeartbeatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, WorkflowService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) FailTask(ctx context.Context, in *FailTaskRequest, opts ...grpc.CallOption) (*FailTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailTaskResponse)
	err := c.cc.Invoke(ctx, WorkflowService_FailTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*ExecutionStateMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionStateMsg)
	err := c.cc.Invoke(ctx, WorkflowService_GetExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetExecutionHistory(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*ExecutionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionHistoryResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetExecutionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionsResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
// All implementations must embed UnimplementedWorkflowServiceServer
// for forward compatibility.
type WorkflowServiceServer interface {
	// SubmitWorkflow durably enqueues a new workflow execution. Submitting an
	// id that already exists is an idempotent no-op (already_exists = true).
	// In cluster mode, returns FailedPrecondition with a NotLeaderError detail
	// when this node does not own the execution's shard.
	SubmitWorkflow(context.Context, *SubmitWorkflowRequest) (*SubmitWorkflowResponse, error)
	// LeaseTask hands the oldest pending execution of the given task type to a
	// worker. The lease is recorded on the log before the worker sees it. When
	// no work is pending the call long-polls up to wait_ms, then returns
	// found = false. Set max_tasks > 1 to lease a batch in one round trip;
	// every lease is still an individual durable log event.
	LeaseTask(context.Context, *LeaseTaskRequest) (*LeaseTaskResponse, error)
	// SubmitWorkflows durably enqueues a batch of executions in one round
	// trip, amortizing RPC overhead for high-rate producers. Each submit is
	// an individual durable log event. In cluster mode every execution in
	// the batch must route to this node.
	SubmitWorkflows(context.Context, *SubmitWorkflowsRequest) (*SubmitWorkflowsResponse, error)
	// CompleteTasks records a batch of completions in one round trip; each
	// completion passes the same exactly-once gate as CompleteTask.
	CompleteTasks(context.Context, *CompleteTasksRequest) (*CompleteTasksResponse, error)
	// HeartbeatTask extends a running lease. valid = false tells the worker its
	// lease is gone (expired or superseded) and it should abandon the attempt.
	HeartbeatTask(context.Context, *HeartbeatTaskRequest) (*HeartbeatTaskResponse, error)
	// CompleteTask records a successful result exactly once. A completion for
	// a stale attempt or an already-terminal execution is rejected with
	// accepted = false (and duplicate = true when the execution already
	// completed), so a zombie worker whose lease expired cannot double-commit.
	CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error)
	// FailTask records a failed attempt. Retryable failures re-enqueue the
	// execution until max_attempts is exhausted; the response says whether a
	// retry was scheduled.
	FailTask(context.Context, *FailTaskRequest) (*FailTaskResponse, error)
	// GetExecution returns the current state of one execution.
	GetExecution(context.Context, *GetExecutionRequest) (*ExecutionStateMsg, error)
	// GetExecutionHistory returns the ordered state transitions of one
	// execution as rebuilt from the event log - the deterministic replay
	// surface used for debugging.
	GetExecutionHistory(context.Context, *GetExecutionRequest) (*ExecutionHistoryResponse, error)
	// ListExecutions returns execution summaries, optionally filtered by
	// status, plus in-flight counts.
	ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error)
	mustEmbedUnimplementedWorkflowServiceServer()
}

// UnimplementedWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServiceServer struct{}

func (UnimplementedWorkflowServiceServer) SubmitWorkflow(context.Context, *SubmitWorkflowRequest) (*SubmitWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitWorkflow not implemented")
}
func (UnimplementedWorkflowServiceServer) LeaseTask(context.Context, *LeaseTaskRequest) (*LeaseTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseTask not implemented")
}
func (UnimplementedWorkflowServiceServer) SubmitWorkflows(context.Context, *SubmitWorkflowsRequest) (*SubmitWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitWorkflows not implemented")
}
func (UnimplementedWorkflowServiceServer) CompleteTasks(context.Context, *CompleteTasksRequest) (*CompleteTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTasks not implemented")
}
func (UnimplementedWorkflowServiceServer) HeartbeatTask(context.Context, *HeartbeatTaskRequest) (*HeartbeatTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HeartbeatTask not implemented")
}
func (UnimplementedWorkflowServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedWorkflowServiceServer) FailTask(context.Context, *FailTaskRequest) (*FailTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailTask not implemented")
}
func (UnimplementedWorkflowServiceServer) GetExecution(context.Context, *GetExecutionRequest) (*ExecutionStateMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecution not implemented")
}
func (UnimplementedWorkflowServiceServer) GetExecutionHistory(context.Context, *GetExecutionRequest) (*ExecutionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecutionHistory not implemented")
}
func (UnimplementedWorkflowServiceServer) ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExecutions not implemented")
}
func (UnimplementedWorkflowServiceServer) mustEmbedUnimplementedWorkflowServiceServer() {}
func (UnimplementedWorkflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServiceServer will
// result in compilation errors.
type UnsafeWorkflowServiceServer interface {
	mustEmbedUnimplementedWorkflowServiceServer()
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowService_ServiceDesc, srv)
}

func _WorkflowService_SubmitWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).SubmitWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_SubmitWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).SubmitWorkflow(ctx, req.(*SubmitWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_LeaseTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).LeaseTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_LeaseTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).LeaseTask(ctx, req.(*LeaseTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_SubmitWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).SubmitWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_SubmitWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).SubmitWorkflows(ctx, req.(*SubmitWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CompleteTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CompleteTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CompleteTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CompleteTasks(ctx, req.(*CompleteTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_HeartbeatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).HeartbeatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_HeartbeatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).HeartbeatTask(ctx, req.(*HeartbeatTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_FailTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).FailTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_FailTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).FailTask(ctx, req.(*FailTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetExecution(ctx, req.(*GetExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetExecutionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetExecutionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetExecutionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetExecutionHistory(ctx, req.(*GetExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListExecutions(ctx, req.(*ListExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowService_ServiceDesc is the grpc.ServiceDesc for WorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goqueue.v1.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitWorkflow",
			Handler:    _WorkflowService_SubmitWorkflow_Handler,
		},
		{
			MethodName: "LeaseTask",
			Handler:    _WorkflowService_LeaseTask_Handler,
		},
		{
			MethodName: "SubmitWorkflows",
			Handler:    _WorkflowService_SubmitWorkflows_Handler,
		},
		{
			MethodName: "CompleteTasks",
			Handler:    _WorkflowService_CompleteTasks_Handler,
		},
		{
			MethodName: "HeartbeatTask",
			Handler:    _WorkflowService_HeartbeatTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _WorkflowService_CompleteTask_Handler,
		},
		{
			MethodName: "FailTask",
			Handler:    _WorkflowService_FailTask_Handler,
		},
		{
			MethodName: "GetExecution",
			Handler:    _WorkflowService_GetExecution_Handler,
		},
		{
			MethodName: "GetExecutionHistory",
			Handler:    _WorkflowService_GetExecutionHistory_Handler,
		},
		{
			MethodName: "ListExecutions",
			Handler:    _WorkflowService_ListExecutions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goqueue.proto",
}
